on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to build (e.g., v1.0.0)'
        required: true

name: Build and Push Docker Image on Tag

jobs:
  BuildImage:
    name: ğŸ™ ğŸ—ï¸ Build Production Image
    runs-on: ubuntu-latest
    env:
      BUILD_ENV: production
    steps:
      - name: ğŸ“– ğŸ” Checkout Repository Code
        uses: actions/checkout@v5

      - name: ğŸ”‘ ğŸ” Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: ğŸ—ï¸ ğŸ”§ Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: ğŸ› ï¸ ğŸš€ Build Production Image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          sbom: true
          provenance: true
          context: .
          tags: siteworxpro/zaparoo-designer:${{ github.event.inputs.tag }}, siteworxpro/zaparoo-designer:latest
